#!/bin/bash

umask 027

export PS1='\[\e[32m\]\u@\h\[\e[33m\]\w\[\e[0m\]:'

alias df='df -h'
alias du='du -sh'

alias grep='egrep -nr --color'
alias egrep='egrep --color=auto'

alias dir='ls --color=auto --format=vertical'
alias vdir='ls --color=auto --format=long'

export LS_OPTIONS='-hFS --color=auto'
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -lA'
alias l='ls $LS_OPTIONS -l'
alias la='ls $LS_OPTIONS -al'

export EDITOR=vim

